# Generated by Django 2.2 on 2019-04-17 15:47

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название категории')),
                ('url', models.SlugField(blank=True, help_text='Если оставить пустым, ссылка будет сгенерирована из названия. Должна быть уникальной.', max_length=30, null=True, unique=True, verbose_name='Ссылка категории')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_category_children', to='catalogue.ProductCategory', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория продукта',
                'verbose_name_plural': 'Категории продукта',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название продукта')),
                ('url', models.SlugField(blank=True, help_text='Если оставить пустым, ссылка будет сгенерирована из названия. Должна быть уникальной.', max_length=30, null=True, unique=True, verbose_name='Ссылка продукта')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Короткое описание продукта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Подробное описание продукта')),
                ('price', models.FloatField(verbose_name='Цена продукта')),
                ('category', models.ManyToManyField(related_name='product_category', to='catalogue.ProductCategory', verbose_name='Категория продукта')),
            ],
            options={
                'verbose_name': 'Продукты Greenway',
                'verbose_name_plural': 'Продукты Greenway',
            },
        ),
    ]
