# Generated by Django 2.2 on 2019-04-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/%Y-%m-%d/', verbose_name='Изображение продукта'),
        ),
    ]
