# Generated by Django 2.2 on 2019-04-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_category', to='catalogue.ProductCategory', verbose_name='Категория продукта'),
        ),
    ]
