# Generated by Django 2.2 on 2019-04-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_auto_20190418_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.SlugField(blank=True, help_text='Если оставить пустым, ссылка будет сгенерирована из названия. Должна быть уникальной.', max_length=100, null=True, unique=True, verbose_name='Ссылка продукта'),
        ),
    ]
