# Generated by Django 2.2 on 2019-04-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_auto_20190420_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/catalog/category', verbose_name='Изображение категории'),
        ),
    ]
