# Generated by Django 2.2 on 2019-04-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_auto_20190420_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание категории'),
        ),
    ]
