# Generated by Django 2.2 on 2019-04-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_productcategory_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/catalog/products/%Y-%m-%d/', verbose_name='Маленькое изображение продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/catalog/products/%Y-%m-%d/', verbose_name='Большое изображение продукта'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Короткое описание категории'),
        ),
    ]
