# Generated by Django 2.2 on 2019-04-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_auto_20190420_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/catalog/products/thumb/%Y-%m-%d/', verbose_name='Маленькое изображение продукта'),
        ),
    ]
