# Generated by Django 2.2 on 2019-04-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_auto_20190420_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='articul',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Артикул'),
        ),
    ]
