# Generated by Django 2.2 on 2019-04-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_productcategory_articul'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='articul',
        ),
        migrations.AddField(
            model_name='product',
            name='articul',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Артикул'),
        ),
    ]
