# Generated by Django 2.2 on 2019-04-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_auto_20190422_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='articul',
            new_name='vendor_code',
        ),
        migrations.AddField(
            model_name='product',
            name='sub_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок продукта'),
        ),
    ]
