# Generated by Django 2.2 on 2019-04-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemenu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='is_index_page',
            field=models.BooleanField(default=False, verbose_name='Главная страница'),
        ),
    ]
