# Generated by Django 2.1 on 2019-04-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemenu', '0002_menuitems_is_index_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='Показывать на сайте'),
        ),
        migrations.AddField(
            model_name='menuitems',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета описание'),
        ),
        migrations.AddField(
            model_name='menuitems',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета ключевые слова'),
        ),
        migrations.AddField(
            model_name='menuitems',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета заголовок'),
        ),
    ]
