# Generated by Django 2.1 on 2019-04-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemenu', '0003_auto_20190426_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='is_cataloque_link',
            field=models.BooleanField(default=False, verbose_name='Ссылка на каталог'),
        ),
    ]
