# Generated by Django 2.1 on 2019-04-26 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitemenu', '0004_menuitems_is_cataloque_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitems',
            old_name='is_cataloque_link',
            new_name='is_catalogue_link',
        ),
    ]
