# Generated by Django 2.1 on 2019-04-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemenu', '0005_auto_20190426_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='is_delivery_link',
            field=models.BooleanField(default=False, verbose_name='Ссылка на доставку'),
        ),
    ]
