# Generated by Django 2.1 on 2019-04-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemenu', '0006_menuitems_is_delivery_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
