# Generated by Django 2.1 on 2019-04-27 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CenterInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_name', models.CharField(max_length=10, verbose_name='Название центра')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес центра')),
                ('openning_hours', models.CharField(max_length=255, verbose_name='Часы работы')),
            ],
            options={
                'verbose_name': 'Информация о центре',
                'verbose_name_plural': 'Информация о центре',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100, verbose_name='Название города')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.AddField(
            model_name='centerinfo',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regional_centers.City', verbose_name='Город'),
        ),
    ]
