# Generated by Django 2.1 on 2019-04-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regional_centers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centerinfo',
            name='center_name',
            field=models.CharField(max_length=100, verbose_name='Название центра'),
        ),
    ]
