# Generated by Django 2.1 on 2019-04-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regional_centers', '0002_auto_20190427_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centerinfo',
            name='openning_hours',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Часы работы'),
        ),
    ]
