# Generated by Django 2.1 on 2019-04-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regional_centers', '0003_auto_20190427_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centerinfo',
            options={'ordering': ('center_name',), 'verbose_name': 'Информация о центре', 'verbose_name_plural': 'Информация о центре'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('city_name',), 'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterField(
            model_name='centerinfo',
            name='openning_hours',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Режим работы'),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название города'),
        ),
    ]
