# Generated by Django 2.2 on 2019-04-22 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0014_auto_20190422_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('email', models.CharField(max_length=100, verbose_name='Электронный адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('zip_code', models.CharField(max_length=6, verbose_name='Почтовый индекс')),
                ('status', models.CharField(choices=[('INPROCESS', 'В обработке'), ('PAYED', 'Оплачено'), ('SHIPPING', 'Доставка'), ('DONE', 'Выполнено'), ('ABORT', 'Отменено')], default='INPROCESS', max_length=15, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_price', models.FloatField(verbose_name='Цена товара')),
                ('quantity', models.IntegerField(verbose_name='Количество товара')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Заказанные продукты',
                'verbose_name_plural': 'Заказанные продукты',
            },
        ),
    ]
