# Generated by Django 2.2 on 2019-04-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-id',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='zip_code',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('INPROCESS', 'В обработке'), ('DONE', 'Выполнено'), ('ABORT', 'Отменено')], default='INPROCESS', max_length=15, verbose_name='Статус'),
        ),
    ]
